module.exports =
  LogicalAddress:
    TV:               0
    RECORDINGDEVICE1: 1
    RECORDINGDEVICE2: 2
    TUNER1:           3
    PLAYBACKDEVICE1:  4
    AUDIOSYSTEM:      5
    TUNER2:           6
    TUNER3:           7
    PLAYBACKDEVICE2:  8
    RECORDINGDEVICE3: 9
    TUNER4:           10
    PLAYBACKDEVICE3:  11
    RESERVED1:        12
    RESERVED2:        13
    FREEUSE:          14
    UNREGISTERED:     15 # initiator
    BROADCAST:        15 # target

  Opcode:
    ACTIVE_SOURCE:                 0x82
    IMAGE_VIEW_ON:                 0x04
    TEXT_VIEW_ON:                  0x0D
    INACTIVE_SOURCE:               0x9D
    REQUEST_ACTIVE_SOURCE:         0x85
    ROUTING_CHANGE:                0x80
    ROUTING_INFORMATION:           0x81
    SET_STREAM_PATH:               0x86
    STANDBY:                       0x36
    RECORD_OFF:                    0x0B
    RECORD_ON:                     0x09
    RECORD_STATUS:                 0x0A
    RECORD_TV_SCREEN:              0x0F
    CLEAR_ANALOGUE_TIMER:          0x33
    CLEAR_DIGITAL_TIMER:           0x99
    CLEAR_EXTERNAL_TIMER:          0xA1
    SET_ANALOGUE_TIMER:            0x34
    SET_DIGITAL_TIMER:             0x97
    SET_EXTERNAL_TIMER:            0xA2
    SET_TIMER_PROGRAM_TITLE:       0x67
    TIMER_CLEARED_STATUS:          0x43
    TIMER_STATUS:                  0x35
    CEC_VERSION:                   0x9E
    GET_CEC_VERSION:               0x9F
    GIVE_PHYSICAL_ADDRESS:         0x83
    GET_MENU_LANGUAGE:             0x91
    REPORT_PHYSICAL_ADDRESS:       0x84
    SET_MENU_LANGUAGE:             0x32
    DECK_CONTROL:                  0x42
    DECK_STATUS:                   0x1B
    GIVE_DECK_STATUS:              0x1A
    PLAY:                          0x41
    GIVE_TUNER_DEVICE_STATUS:      0x08
    SELECT_ANALOGUE_SERVICE:       0x92
    SELECT_DIGITAL_SERVICE:        0x93
    TUNER_DEVICE_STATUS:           0x07
    TUNER_STEP_DECREMENT:          0x06
    TUNER_STEP_INCREMENT:          0x05
    DEVICE_VENDOR_ID:              0x87
    GIVE_DEVICE_VENDOR_ID:         0x8C
    VENDOR_COMMAND:                0x89
    VENDOR_COMMAND_WITH_ID:        0xA0
    VENDOR_REMOTE_BUTTON_DOWN:     0x8A
    VENDOR_REMOTE_BUTTON_UP:       0x8B
    SET_OSD_STRING:                0x64
    GIVE_OSD_NAME:                 0x46
    SET_OSD_NAME:                  0x47
    MENU_REQUEST:                  0x8D
    MENU_STATUS:                   0x8E
    USER_CONTROL_PRESSED:          0x44
    USER_CONTROL_RELEASE:          0x45
    GIVE_DEVICE_POWER_STATUS:      0x8F
    REPORT_POWER_STATUS:           0x90
    FEATURE_ABORT:                 0x00
    ABORT:                         0xFF
    GIVE_AUDIO_STATUS:             0x71
    GIVE_SYSTEM_AUDIO_MODE_STATUS: 0x7D
    REPORT_AUDIO_STATUS:           0x7A
    SET_SYSTEM_AUDIO_MODE:         0x72
    SYSTEM_AUDIO_MODE_REQUEST:     0x70
    SYSTEM_AUDIO_MODE_STATUS:      0x7E
    SET_AUDIO_RATE:                0x9A

    # CEC 1.4
    START_ARC:                     0xC0
    REPORT_ARC_STARTED:            0xC1
    REPORT_ARC_ENDED:              0xC2
    REQUEST_ARC_START:             0xC3
    REQUEST_ARC_END:               0xC4
    END_ARC:                       0xC5
    CDC:                           0xF8
    NONE:                          0xFD
