// Generated by CoffeeScript 1.9.3
(function() {
  var emitLines;

  emitLines = function(stream) {
    var backlog;
    backlog = '';
    stream.on('data', function(data) {
      var n, results;
      backlog += data;
      n = backlog.indexOf('\n');
      results = [];
      while (~n) {
        stream.emit('line', backlog.substring(0, n));
        backlog = backlog.substring(n + 1);
        results.push(n = backlog.indexOf('\n'));
      }
      return results;
    });
    return stream.on('end', function() {
      if (backlog) {
        return stream.emit('line', backlog);
      }
    });
  };

  module.exports = emitLines;

}).call(this);
